/* ReelFeel - Catálogo de Filmes */

const MOVIES = [
    // ========== CLÁSSICOS ==========
    {
        id: 1,
        title: 'Forrest Gump',
        year: 1994,
        genres: ['Drama', 'Romance', 'Comédia'],
        style: 'classico',
        category: 'Drama',
        description: 'A história de um homem com QI abaixo da média que, sem querer, testemunha e influencia vários momentos históricos dos Estados Unidos.',
        intensity: 2,
        complexity: 2,
        duration: '2h 22min',
        trailerId: 'bLvqoHBptjg',
        platformRating: 4.8,
        poster: 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
        top10: true
    },
    {
        id: 2,
        title: 'O Poderoso Chefão',
        year: 1972,
        genres: ['Drama', 'Crime'],
        style: 'classico',
        category: 'Drama',
        description: 'O patriarca de uma dinastia do crime organizado transfere o controle de seu império clandestino para seu filho relutante.',
        intensity: 4,
        complexity: 4,
        duration: '2h 55min',
        trailerId: 'sY1S34973zA',
        platformRating: 4.9,
        poster: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
        top10: true
    },
    {
        id: 3,
        title: 'Um Sonho de Liberdade',
        year: 1994,
        genres: ['Drama', 'Crime'],
        style: 'classico',
        category: 'Drama',
        description: 'Dois homens presos criam laços ao longo de vários anos, encontrando consolo e eventual redenção através de atos de decência comum.',
        intensity: 3,
        complexity: 3,
        duration: '2h 22min',
        trailerId: '6hB3S9bIaco',
        platformRating: 4.9,
        poster: 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
        top10: true
    },
    {
        id: 4,
        title: 'Pulp Fiction',
        year: 1994,
        genres: ['Crime', 'Drama', 'Comédia'],
        style: 'drama',
        category: 'Drama',
        description: 'As vidas de dois assassinos da máfia, um boxeador, a esposa de um gângster e dois bandidos se entrelaçam em quatro histórias de violência e redenção.',
        intensity: 4,
        complexity: 4,
        duration: '2h 34min',
        trailerId: 's7EdQ4FqbhY',
        platformRating: 4.7,
        poster: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
        top10: true
    },
    {
        id: 5,
        title: 'Clube da Luta',
        year: 1999,
        genres: ['Drama', 'Thriller'],
        style: 'drama',
        category: 'Drama',
        description: 'Um funcionário de escritório insone e um fabricante de sabão formam um clube de luta clandestino que evolui para muito mais.',
        intensity: 5,
        complexity: 5,
        duration: '2h 19min',
        trailerId: 'qtRKdVHc-cE',
        platformRating: 4.7,
        poster: 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
        top10: true
    },
    {
        id: 6,
        title: 'A Lista de Schindler',
        year: 1993,
        genres: ['Drama', 'História', 'Guerra'],
        style: 'classico',
        category: 'Drama',
        description: 'Na Polônia ocupada pelos alemães durante a Segunda Guerra Mundial, Oskar Schindler se preocupa com sua força de trabalho judaica após testemunhar sua perseguição.',
        intensity: 5,
        complexity: 3,
        duration: '3h 15min',
        trailerId: 'gG22XNhtnoY',
        platformRating: 4.9,
        poster: 'https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
        top10: true
    },

    // ========== THRILLERS E ÉPICOS ==========
    {
        id: 7,
        title: 'Batman: O Cavaleiro das Trevas',
        year: 2008,
        genres: ['Ação', 'Crime', 'Drama'],
        style: 'thriller',
        category: 'Thriller',
        description: 'Batman aceita mais um grande teste em sua luta contra o crime em Gotham City quando o Coringa emerge das sombras para causar caos.',
        intensity: 5,
        complexity: 4,
        duration: '2h 32min',
        trailerId: 'EXeTwQWrcwY',
        platformRating: 4.8,
        poster: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        top10: true
    },
    {
        id: 8,
        title: 'Matrix',
        year: 1999,
        genres: ['Ação', 'Ficção Científica'],
        style: 'ficcao',
        category: 'Thriller',
        description: 'Um hacker descobre que a realidade é uma simulação criada por máquinas e junta-se à rebelião para libertar a humanidade.',
        intensity: 4,
        complexity: 4,
        duration: '2h 16min',
        trailerId: 'vKQi3bBA1y8',
        platformRating: 4.6,
        poster: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
        top10: true
    },
    {
        id: 9,
        title: 'Gladiador',
        year: 2000,
        genres: ['Ação', 'Drama', 'Aventura'],
        style: 'epico',
        category: 'Thriller',
        description: 'Um general romano traído pelo filho do imperador é forçado a se tornar escravo e gladiador, buscando vingança.',
        intensity: 5,
        complexity: 3,
        duration: '2h 35min',
        trailerId: 'owK1qxDselE',
        platformRating: 4.6,
        poster: 'https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg',
        top10: true
    },
    {
        id: 10,
        title: 'Gladiador 2',
        year: 2024,
        genres: ['Ação', 'Drama', 'Aventura'],
        style: 'epico',
        category: 'Thriller',
        description: 'A continuação épica da saga do Coliseu, com novos heróis enfrentando o poder de Roma.',
        intensity: 4,
        complexity: 3,
        duration: '2h 28min',
        trailerId: 'cXg62-t8BWs',
        platformRating: 4.3,
        poster: 'https://image.tmdb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg',
        top10: false
    },

    // ========== FICÇÃO CIENTÍFICA ==========
    {
        id: 11,
        title: 'Interestelar',
        year: 2014,
        genres: ['Ficção Científica', 'Drama', 'Aventura'],
        style: 'ficcao',
        category: 'Thriller',
        description: 'Uma equipe de exploradores viaja através de um buraco de minhoca no espaço em busca de um novo lar para a humanidade.',
        intensity: 4,
        complexity: 5,
        duration: '2h 49min',
        trailerId: 'zSWdZVtXT7E',
        platformRating: 4.8,
        poster: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        top10: true
    },
    {
        id: 12,
        title: 'A Origem',
        year: 2010,
        genres: ['Ficção Científica', 'Ação', 'Thriller'],
        style: 'ficcao',
        category: 'Thriller',
        description: 'Um ladrão que rouba segredos corporativos através do uso de tecnologia de compartilhamento de sonhos recebe a tarefa inversa de plantar uma ideia.',
        intensity: 4,
        complexity: 5,
        duration: '2h 28min',
        trailerId: 'YoHD9XEInc0',
        platformRating: 4.7,
        poster: 'https://image.tmdb.org/t/p/w500/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg',
        top10: true
    },
    {
        id: 13,
        title: 'Duna: Parte 2',
        year: 2024,
        genres: ['Ficção Científica', 'Aventura', 'Drama'],
        style: 'epico',
        category: 'Thriller',
        description: 'Paul Atreides se une aos Fremen para vingar a destruição de sua família enquanto tenta evitar um futuro terrível.',
        intensity: 4,
        complexity: 4,
        duration: '2h 46min',
        trailerId: 'Way9Dexny3w',
        platformRating: 4.7,
        poster: 'https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg',
        top10: true
    },
    {
        id: 14,
        title: 'Blade Runner 2049',
        year: 2017,
        genres: ['Ficção Científica', 'Drama', 'Mistério'],
        style: 'ficcao',
        category: 'Thriller',
        description: 'Um jovem blade runner descobre um segredo há muito enterrado que o leva a encontrar Rick Deckard, desaparecido há 30 anos.',
        intensity: 3,
        complexity: 4,
        duration: '2h 44min',
        trailerId: 'gCcx85zbxz4',
        platformRating: 4.5,
        poster: 'https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
        top10: false
    },

    // ========== FANTASIA / AVENTURA ==========
    {
        id: 15,
        title: 'O Senhor dos Anéis: O Retorno do Rei',
        year: 2003,
        genres: ['Fantasia', 'Aventura', 'Drama'],
        style: 'epico',
        category: 'Drama',
        description: 'Gandalf e Aragorn lideram o Mundo dos Homens contra o exército de Sauron para desviar o olhar de Frodo e Sam enquanto se aproximam de Mordor.',
        intensity: 5,
        complexity: 4,
        duration: '3h 21min',
        trailerId: 'r5X-hFf6Bwo',
        platformRating: 4.9,
        poster: 'https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
        top10: true
    },
    {
        id: 16,
        title: 'O Senhor dos Anéis: As Duas Torres',
        year: 2002,
        genres: ['Fantasia', 'Aventura', 'Drama'],
        style: 'epico',
        category: 'Drama',
        description: 'Enquanto Frodo e Sam se aproximam de Mordor com a ajuda de Gollum, a Sociedade separada enfrenta Saruman e suas hordas de Isengard.',
        intensity: 5,
        complexity: 4,
        duration: '2h 59min',
        trailerId: 'LbfMDwc4azU',
        platformRating: 4.8,
        poster: 'https://image.tmdb.org/t/p/w500/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg',
        top10: true
    },
    {
        id: 17,
        title: 'O Senhor dos Anéis: A Sociedade do Anel',
        year: 2001,
        genres: ['Fantasia', 'Aventura', 'Drama'],
        style: 'epico',
        category: 'Drama',
        description: 'Um hobbit da comarca do Condado e oito companheiros partem em uma jornada para destruir o poderoso Um Anel e salvar a Terra-média.',
        intensity: 4,
        complexity: 4,
        duration: '2h 58min',
        trailerId: 'V75dMMIW2B4',
        platformRating: 4.8,
        poster: 'https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg',
        top10: true
    },
    {
        id: 18,
        title: 'Star Wars: Uma Nova Esperança',
        year: 1977,
        genres: ['Ficção Científica', 'Aventura', 'Ação'],
        style: 'classico',
        category: 'Thriller',
        description: 'Luke Skywalker se junta a forças com um Cavaleiro Jedi, um piloto arrogante, um Wookiee e dois droides para salvar a galáxia.',
        intensity: 3,
        complexity: 2,
        duration: '2h 1min',
        trailerId: 'vZ734NWnAHA',
        platformRating: 4.6,
        poster: 'https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg',
        top10: true
    },

    // ========== THRILLER / SUSPENSE ==========
    {
        id: 19,
        title: 'O Silêncio dos Inocentes',
        year: 1991,
        genres: ['Thriller', 'Crime', 'Drama'],
        style: 'thriller',
        category: 'Thriller',
        description: 'Uma jovem agente do FBI busca a ajuda de um brilhante psiquiatra canibal encarcerado para capturar outro serial killer.',
        intensity: 5,
        complexity: 4,
        duration: '1h 58min',
        trailerId: 'W6Mm8Sbe__o',
        platformRating: 4.7,
        poster: 'https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg',
        top10: true
    },
    {
        id: 20,
        title: 'Se7en: Os Sete Crimes Capitais',
        year: 1995,
        genres: ['Thriller', 'Crime', 'Mistério'],
        style: 'thriller',
        category: 'Thriller',
        description: 'Dois detetives caçam um assassino em série que usa os sete pecados capitais como motivo de seus crimes.',
        intensity: 5,
        complexity: 4,
        duration: '2h 7min',
        trailerId: 'znmZoVkCjpI',
        platformRating: 4.7,
        poster: 'https://image.tmdb.org/t/p/w500/6yoghtyTpznpBik8EngEmJskVUO.jpg',
        top10: true
    },
    {
        id: 21,
        title: 'O Sexto Sentido',
        year: 1999,
        genres: ['Thriller', 'Drama', 'Mistério'],
        style: 'thriller',
        category: 'Thriller',
        description: 'Um menino que consegue ver e falar com os mortos procura a ajuda de um psicólogo infantil desanimado.',
        intensity: 3,
        complexity: 4,
        duration: '1h 47min',
        trailerId: 'VG9AGf66tXM',
        platformRating: 4.5,
        poster: 'https://image.tmdb.org/t/p/w500/fIssD3w3SvIhPPmVo4WMgZDVLID.jpg',
        top10: false
    },

    // ========== ANIMAÇÃO ==========
    {
        id: 22,
        title: 'O Rei Leão',
        year: 1994,
        genres: ['Animação', 'Aventura', 'Drama'],
        style: 'animacao',
        category: 'Animação',
        description: 'O príncipe leão Simba foge de seu reino após a morte de seu pai, apenas para aprender o verdadeiro significado de responsabilidade e bravura.',
        intensity: 2,
        complexity: 2,
        duration: '1h 28min',
        trailerId: 'lFzVJEksyvY',
        platformRating: 4.6,
        poster: 'https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg',
        top10: true
    },
    {
        id: 23,
        title: 'Spirited Away: A Viagem de Chihiro',
        year: 2001,
        genres: ['Animação', 'Fantasia', 'Aventura'],
        style: 'animacao',
        category: 'Animação',
        description: 'Durante a mudança de sua família para os subúrbios, uma garota de 10 anos entra no mundo dos deuses, bruxas e espíritos.',
        intensity: 2,
        complexity: 3,
        duration: '2h 5min',
        trailerId: 'ByXuk9QqQkk',
        platformRating: 4.8,
        poster: 'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
        top10: true
    },
    {
        id: 24,
        title: 'Toy Story',
        year: 1995,
        genres: ['Animação', 'Aventura', 'Comédia'],
        style: 'animacao',
        category: 'Animação',
        description: 'O caubói Woody fica com ciúmes e tenta se livrar de Buzz Lightyear, o novo brinquedo de Andy.',
        intensity: 1,
        complexity: 2,
        duration: '1h 21min',
        trailerId: 'rNk1Wi8SvNc',
        platformRating: 4.5,
        poster: 'https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg',
        top10: false
    },

    // ========== DRAMA ==========
    {
        id: 26,
        title: 'O Poderoso Chefão: Parte II',
        year: 1974,
        genres: ['Drama', 'Crime'],
        style: 'classico',
        category: 'Drama',
        description: 'A história paralela da família Corleone: a ascensão do jovem Vito e a consolidação do império por Michael.',
        intensity: 4,
        complexity: 5,
        duration: '3h 22min',
        trailerId: '9O1Iy9od7-A',
        platformRating: 4.8,
        poster: 'https://image.tmdb.org/t/p/w500/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
        top10: true
    },
    {
        id: 27,
        title: 'Parasita',
        year: 2019,
        genres: ['Drama', 'Thriller', 'Comédia'],
        style: 'drama',
        category: 'Drama',
        description: 'Uma família pobre arquiteta um plano para se infiltrar na casa de uma família rica, resultando em consequências inesperadas.',
        intensity: 4,
        complexity: 4,
        duration: '2h 12min',
        trailerId: '5xH0HfJHsaY',
        platformRating: 4.7,
        poster: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
        top10: true
    },
    {
        id: 28,
        title: 'Coringa',
        year: 2019,
        genres: ['Drama', 'Crime', 'Thriller'],
        style: 'drama',
        category: 'Drama',
        description: 'Em Gotham City, o comediante Arthur Fleck é ignorado e maltratado pela sociedade, iniciando uma espiral descendente de violência.',
        intensity: 5,
        complexity: 4,
        duration: '2h 2min',
        trailerId: 'zAGVQLHvwOY',
        platformRating: 4.6,
        poster: 'https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
        top10: true
    },

    // ========== COMÉDIA ==========
    {
        id: 29,
        title: 'De Volta para o Futuro',
        year: 1985,
        genres: ['Comédia', 'Aventura', 'Ficção Científica'],
        style: 'classico',
        category: 'Drama',
        description: 'Marty McFly é acidentalmente enviado para 1955 em uma máquina do tempo e deve garantir que seus pais se apaixonem para poder voltar ao futuro.',
        intensity: 2,
        complexity: 3,
        duration: '1h 56min',
        trailerId: 'qvsgGtivCgs',
        platformRating: 4.6,
        poster: 'https://image.tmdb.org/t/p/w500/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg',
        top10: true
    },
    {
        id: 30,
        title: 'Se Beber, Não Case!',
        year: 2009,
        genres: ['Comédia'],
        style: 'drama',
        category: 'Drama',
        description: 'Três padrinhos acordam após uma despedida de solteiro em Las Vegas sem lembrar de nada, com o noivo desaparecido.',
        intensity: 3,
        complexity: 2,
        duration: '1h 40min',
        trailerId: 'tcdUhdOlz9M',
        platformRating: 4.2,
        poster: 'https://image.tmdb.org/t/p/w500/uluhlXubGu1VxU63X9VHCLWDAYP.jpg',
        top10: false
    }
];
